[package]
name = "types"
version = "0.1.0"
edition = "2024"

[features]
validator = ["dep:validator"]

[dependencies]
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = "1.16.0"
validator = { version = "0.20.0", optional = true }
